require("config.nvim-autopairs")
require("config.lualine")
require("config.colorscheme")
require("config.telescope")
require("config.nvim-tree")
require("config.lsp")
require("config.treesitter")
require("config.which-key")
require("config.trouble")
require("config.cmp")
require('config.bufferline')
-- require('config.noice')
require("config.lspsaga")
-- require("config.indent-blankline")
require("config.fidget")
require("config.neorg")
